### PR TITLE
Fix for ViewPagerAdapter, getItemPosition calls equals instead of ==.

### PR DESCRIPTION
**Pull request by dozd**
Hi, I've changed finding item position in ViewPagerAdater to work with objects having their equals overridden.

### CODE REVIEW

**Comment by evant** [comment]
What issue were you running into? I believe I did this because you could have 2 equal items in the pager and it could select the wrong one.

**Comment by dozd** [comment]
Ahh, you're right, that would be issue. I got no update to ViewPager when updated item `ObservableArrayList` with set(index, item). At first i thought i got bad position, but its not the issue (i was confused by wrong debugger session), i must investigate further :-/. Sorry for not tested before pr.

**Comment by dozd** [comment]
By my mistake, that `set(index, item)` to `ObservableArrayList` was added as second item into `ViewPager`. But now, everything is ok and it seems, that change to current displayed item in `ViewPager` doesn't reload it. It looks like feature according to `ViewPager` source code. My wrong.

**Comment by evant** [comment]
`set(index, item)` _should_ refresh that page in the viewpager. If it's not you can open an issue about it.

**Comment by dozd** [comment]
Hm, I'll try create small sample app to test it outside my context.

**Comment by dozd** [comment]
Why you think `ViewPager` should refresh? I don't see nothing to change current item in `ViewPager.dataSetChanged()`.

```java
void dataSetChanged() {
        // This method only gets called if our observer is attached, so mAdapter is non-null.

        final int adapterCount = mAdapter.getCount();
        mExpectedAdapterCount = adapterCount;
        boolean needPopulate = mItems.size() < mOffscreenPageLimit * 2 + 1 &&
                mItems.size() < adapterCount;
        int newCurrItem = mCurItem;

        boolean isUpdating = false;
        for (int i = 0; i < mItems.size(); i++) {
            final ItemInfo ii = mItems.get(i);
            final int newPos = mAdapter.getItemPosition(ii.object);

            if (newPos == PagerAdapter.POSITION_UNCHANGED) {
                continue;
            }

            if (newPos == PagerAdapter.POSITION_NONE) {
                mItems.remove(i);
                i--;

                if (!isUpdating) {
                    mAdapter.startUpdate(this);
                    isUpdating = true;
                }

                mAdapter.destroyItem(this, ii.position, ii.object);
                needPopulate = true;

                if (mCurItem == ii.position) {
                    // Keep the current item in the valid range
                    newCurrItem = Math.max(0, Math.min(mCurItem, adapterCount - 1));
                    needPopulate = true;
                }
                continue;
            }

            if (ii.position != newPos) {
                if (ii.position == mCurItem) {
                    // Our current item changed position. Follow it.
                    newCurrItem = newPos;
                }

                ii.position = newPos;
                needPopulate = true;
            }
        }

        if (isUpdating) {
            mAdapter.finishUpdate(this);
        }

        Collections.sort(mItems, COMPARATOR);

        if (needPopulate) {
            // Reset our known page widths; populate will recompute them.
            final int childCount = getChildCount();
            for (int i = 0; i < childCount; i++) {
                final View child = getChildAt(i);
                final LayoutParams lp = (LayoutParams) child.getLayoutParams();
                if (!lp.isDecor) {
                    lp.widthFactor = 0.f;
                }
            }

            setCurrentItemInternal(newCurrItem, false, true);
            requestLayout();
        }
    }
```

**Comment by evant** [comment]
Well if you change the item `==` will fail and it will return `POSITION_NONE`. This should cause that page to be destroyed and recreated.

**Comment by evant** [comment]
But regardless of what viewpager does if this doesn't work it is a bug. I'll figure out a way to make it work.

**Comment by dozd** [comment]
Thanks, that is the point. I was changing inner state of the object instead of the whole object. So lame :(.
Thank you for your time (and library as well). Keep going.

**Comment by evant** [comment]
Ooh, yeah if you change the inner state you should use observable fields or `@Bindable` getteers.

**Comment by dozd** [comment]
Ahh, yeah :). Thanks man.

**Pull request closed without merging**
